package com.practice.accessmodifiers;

public class PrivateAccessModifierTest {
	public static void main(String[] args) {
		Account account = new Account();
//System.out.println(account.id);		
account.showUser();		


	}
	
	
}


class Account {
	
	//data members : properties 
	private long id = 100001;
	private double balance = 72362.234;
	private String username ="mike123";
	private String password= "mike@123";
	
	//private methods
	private double showBalance() {
		return balance;
	}
	
	public long showId() {
		return id;
	}
	
	public void showUser() {
		System.out.println("The user : "+ username);
			}
	//default constructor - added and generated by compiler ( Account {})
	
}